# problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fib bound
	sum = 0
	val1 = 1
	val2 = 2
	total = val2
	while true
		sum = val1 + val2
		break if sum > bound 
		
		val1 = val2
		val2 = sum
		total += sum if sum%2 == 0
	end

	total
end

puts fib 4000000